"use client";

import { useState, useEffect, Suspense } from 'react';
import { ArrowLeft, Download, Share2 } from 'lucide-react';
import { useRouter, useSearchParams } from 'next/navigation';
import KundaliForm from '@/components/astrology/KundaliForm';
import KundaliChart from '@/components/astrology/KundaliChart';

function KundaliMakingContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [kundali, setKundali] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const generateKundali = async (formData) => {
    setLoading(true);
    setError(null);
    
    try {
      const response = await fetch('/backend/kundali/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData)
      });
      
      const data = await response.json();
      
      if (data.success) {
        setKundali(data.kundali);
      } else {
        setError(data.error || 'Failed to generate Kundali');
      }
    } catch (err) {
      setError('Network error. Please check your connection and try again.');
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate when coming from home page
  useEffect(() => {
    const autoGenerate = searchParams.get('autoGenerate');
    if (autoGenerate === 'true') {
      const formData = {
        name: searchParams.get('name'),
        gender: searchParams.get('gender'),
        date: searchParams.get('date'),
        time: searchParams.get('time'),
        place: searchParams.get('place'),
        lat: Number(searchParams.get('lat')),
        lng: Number(searchParams.get('lng')),
      };

      if (formData.name && formData.date && formData.time && formData.place) {
        generateKundali(formData);
      }
    }
  }, []);

  const handleDownload = () => {
    if (!kundali) return;
    
    const content = `
Kundali Report for ${kundali.personalDetails.name}
======================================

Birth Details:
- Date: ${kundali.personalDetails.date}
- Time: ${kundali.personalDetails.time}
- Place: ${kundali.personalDetails.place}

Ascendant: ${kundali.ascendant.sign} ${kundali.ascendant.degree}°

Planetary Positions:
${Object.entries(kundali.planets).map(([planet, data]) => 
  `- ${planet.charAt(0).toUpperCase() + planet.slice(1)}: ${data.sign} ${data.degree}°${data.minute}'`
).join('\n')}

Generated on: ${new Date().toLocaleDateString()}
Generated by: Free Astrology Services
    `.trim();
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `kundali-${kundali.personalDetails.name.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (!kundali) return;
    
    const shareText = `🌟 Check out my Kundali generated by Free Astrology Services!\n\nAscendant: ${kundali.ascendant.sign}\nMoon Sign: ${kundali.planets.moon.sign}\n\nGenerate yours free at: ${window.location.origin}/astrology/kundali-making`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My Kundali Report',
          text: shareText
        });
      } catch (err) {
        console.log('Share cancelled');
      }
    } else {
      navigator.clipboard.writeText(shareText);
      alert('Kundali details copied to clipboard!');
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      <div className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 py-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <button
                onClick={() => router.back()}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              >
                <ArrowLeft className="w-5 h-5 text-gray-600" />
              </button>
              <div>
                <h1 className="text-2xl md:text-3xl font-bold text-gray-900">
                  Free Kundali Making
                </h1>
                <p className="text-gray-600">Generate your detailed birth chart instantly</p>
              </div>
            </div>

            {kundali && (
              <div className="flex items-center space-x-3">
                <button
                  onClick={handleDownload}
                  className="flex items-center space-x-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
                >
                  <Download className="w-4 h-4" />
                  <span className="hidden sm:inline">Download</span>
                </button>
                <button
                  onClick={handleShare}
                  className="flex items-center space-x-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
                >
                  <Share2 className="w-4 h-4" />
                  <span className="hidden sm:inline">Share</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 py-8">
        {loading ? (
          <div className="bg-white rounded-xl shadow-lg p-8">
            <div className="text-center">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-600 mx-auto mb-4"></div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">Generating Your Kundali</h3>
              <p className="text-gray-600">Calculating planetary positions...</p>
            </div>
          </div>
        ) : error ? (
          <div className="bg-red-50 border border-red-200 rounded-xl p-6">
            <div className="flex items-center space-x-2 text-red-800">
              <span className="text-2xl">⚠️</span>
              <span className="font-semibold">Error</span>
            </div>
            <p className="text-red-700 mt-2">{error}</p>
            <button
              onClick={() => router.push('/astrology/kundali-making')}
              className="mt-4 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
            >
              Try Again
            </button>
          </div>
        ) : kundali ? (
          <KundaliChart kundali={kundali} />
        ) : (
          <div className="max-w-2xl mx-auto">
            <KundaliForm 
              onSubmit={generateKundali}
              loading={loading}
              title="Enter Your Birth Details"
              showGender={true}
            />
          </div>
        )}
      </div>
    </div>
  );
}

export default function KundaliMakingPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <KundaliMakingContent />
    </Suspense>
  );
}