"use client";

import { useState, useEffect, useRef } from 'react';
import { ArrowLeft, Star, Sparkles, Download, Share2, Zap } from 'lucide-react';
import { useSearchParams, useRouter } from 'next/navigation';
import RashiSelector from '@/components/horoscope/RashiSelector';
import PeriodSelector from '@/components/horoscope/PeriodSelector';
import HoroscopeCard from '@/components/horoscope/HoroscopeCard';
import RemediesSection from '@/components/horoscope/RemediesSection';

export default function HoroscopeContent() {
  const router = useRouter();
  const [selectedRashi, setSelectedRashi] = useState(null);
  const [period, setPeriod] = useState('daily');
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [horoscope, setHoroscope] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const RASHI_DATA = {
    aries: { english: "Aries", sanskrit: "मेष" },
    taurus: { english: "Taurus", sanskrit: "वृषभ" },
    gemini: { english: "Gemini", sanskrit: "मिथुन" },
    cancer: { english: "Cancer", sanskrit: "कर्क" },
    leo: { english: "Leo", sanskrit: "सिंह" },
    virgo: { english: "Virgo", sanskrit: "कन्या" },
    libra: { english: "Libra", sanskrit: "तुला" },
    scorpio: { english: "Scorpio", sanskrit: "वृश्चिक" },
    sagittarius: { english: "Sagittarius", sanskrit: "धनु" },
    capricorn: { english: "Capricorn", sanskrit: "मकर" },
    aquarius: { english: "Aquarius", sanskrit: "कुंभ" },
    pisces: { english: "Pisces", sanskrit: "मीन" },
  };
  const searchParams = useSearchParams();
  const rashiParam = searchParams.get("rashi");

  useEffect(() => {
    if (!rashiParam) return;
    const rashi = RASHI_DATA[rashiParam.toLowerCase()];
    if (rashi) {
      setSelectedRashi(rashi);
    }
  }, [rashiParam]);

  useEffect(() => {
    if (selectedRashi) {
      fetchHoroscope();
    }
  }, [selectedRashi, period, selectedDate]);

  const fetchHoroscope = async () => {
    setLoading(true);
    setError(null);

    try {
      const params = new URLSearchParams({
        rashi: selectedRashi.english.toLowerCase(),
        date: selectedDate,
      });

      const response = await fetch(`/backend/horoscope/${period}?${params}`);
      const data = await response.json();

      if (data.success) {
        setHoroscope(data.horoscope);
      } else if (data.quotaExhausted) {
        const seconds = data.retryAfter ?? 60;
        setError(`✨ Our astrologers are busy right now. Please try again in ${seconds} seconds.`);

        setTimeout(() => {
          setError(null);
          fetchHoroscope();
        }, seconds * 1000);
      } else {
        setError(data.error || 'Failed to fetch horoscope');
      }
    } catch (err) {
      setError('Unable to fetch horoscope. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!horoscope || !selectedRashi) return;

    const content = `
${selectedRashi.sanskrit} (${selectedRashi.english}) - ${period.toUpperCase()} Horoscope
Date: ${selectedDate}
Generated by: AI-Powered Vedic Astrology
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🌟 GENERAL PREDICTION:
${horoscope.general}

💰 FINANCE & WEALTH:
${horoscope.finance}

❤️ LOVE & RELATIONSHIPS:
${horoscope.love}

💼 CAREER & PROFESSION:
${horoscope.career}

🏥 HEALTH & WELLNESS:
${horoscope.health}

⭐ RATINGS:
- Finance: ${'⭐'.repeat(horoscope.ratings.finance)}
- Love: ${'⭐'.repeat(horoscope.ratings.love)}
- Career: ${'⭐'.repeat(horoscope.ratings.career)}
- Health: ${'⭐'.repeat(horoscope.ratings.health)}
- Overall: ${'⭐'.repeat(horoscope.overallRating)}

🍀 LUCKY DETAILS:
- Color: ${horoscope.luckyDetails.color}
- Number: ${horoscope.luckyDetails.number}
- Time: ${horoscope.luckyDetails.time}
- Direction: ${horoscope.luckyDetails.direction}
- Gemstone: ${horoscope.luckyDetails.gemstone}
- Mantra: ${horoscope.luckyDetails.mantra}

🕉️ VEDIC REMEDIES:
${horoscope.remedies.map((r, i) => `${i + 1}. ${r}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Visit: ${window.location.origin}/astrology/horoscope
    `.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedRashi.english}-${period}-horoscope-${selectedDate}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (!horoscope || !selectedRashi) return;

    const shareText = `🌟 ${selectedRashi.english} ${period.charAt(0).toUpperCase() + period.slice(1)} Horoscope

${horoscope.general}

⭐ Overall Rating: ${'⭐'.repeat(horoscope.overallRating)}

Get your detailed AI horoscope at: ${window.location.origin}/astrology/horoscope`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: `${selectedRashi.english} ${period} Horoscope`,
          text: shareText
        });
      } catch (err) {
        if (err.name !== 'AbortError') {
          console.log('Share cancelled');
        }
      }
    } else {
      navigator.clipboard.writeText(shareText);
      alert('Horoscope copied to clipboard!');
    }
  };

  return (
    <div className="min-h-screen mt-[104px] bg-background ">

      {/* Header */}
      <div className="bg-primary-main shadow-lg">
        <div className="max-w-7xl mx-auto px-4 py-6">
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center space-x-4">
              <button
                onClick={() => router.back()}
                className="p-2 bg-background/20 hover:bg-background/30 rounded-lg transition-colors"
              >
                <ArrowLeft className="w-5 h-5 text-background" />
              </button>
              <div>
                <h1 className="text-2xl md:text-3xl font-bold text-background flex items-center">
                  <Star className="w-8 h-8 mr-2" />
                  राशिफल - AI Horoscope
                </h1>
                <p className="text-background/80 mt-1 flex items-center gap-2">
                  <Zap className="w-4 h-4 fill-current" />
                  Powered by AI & Vedic Astrology
                </p>
              </div>
            </div>

            {horoscope && (
              <div className="flex items-center space-x-3">
                <button
                  onClick={handleDownload}
                  className="flex items-center space-x-2 px-4 py-2 bg-background/20 hover:bg-background/30 rounded-lg transition-colors text-background"
                >
                  <Download className="w-4 h-4" />
                  <span className="hidden sm:inline">Download</span>
                </button>
                <button
                  onClick={handleShare}
                  className="flex items-center space-x-2 px-4 py-2 bg-background text-primary-main rounded-lg hover:bg-secondary-main transition-colors"
                >
                  <Share2 className="w-4 h-4" />
                  <span className="hidden sm:inline">Share</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 py-8">

        {/* Rashi Selector */}
        <div className="mb-8">
          <RashiSelector
            selectedRashi={selectedRashi}
            onSelect={setSelectedRashi}
          />
        </div>

        {selectedRashi && (
          <>
            {/* Period and Date Selector */}
            <div className="mb-8">
              <PeriodSelector
                period={period}
                setPeriod={setPeriod}
                selectedDate={selectedDate}
                setSelectedDate={setSelectedDate}
              />
            </div>

            {/* Loading State — no spinner, simple text only */}
            {loading && (
              <div className="bg-background rounded-2xl shadow-xl p-12 text-center border border-secondary-dark">
                <p className="text-secondary">Generating your {period} horoscope...</p>
              </div>
            )}

            {/* Error State */}
            {error && (
              <div className="bg-red-main/5 border-2 border-red-main/20 rounded-2xl p-6">
                <div className="flex items-center space-x-2 text-red-main">
                  <span className="text-2xl">⚠️</span>
                  <span className="font-semibold">Error</span>
                </div>
                <p className="text-red-main/80 mt-2">{error}</p>
                <button
                  onClick={fetchHoroscope}
                  className="mt-4 px-4 py-2 bg-red-main text-background rounded-lg hover:bg-red-dark transition-colors"
                >
                  Try Again
                </button>
              </div>
            )}

            {/* Horoscope Display */}
            {!loading && !error && horoscope && (
              <div className="space-y-6">
                <HoroscopeCard
                  rashi={selectedRashi}
                  horoscope={horoscope}
                  period={period}
                  date={selectedDate}
                />

                <RemediesSection
                  remedies={horoscope.remedies}
                  luckyDetails={horoscope.luckyDetails}
                />
              </div>
            )}
          </>
        )}

        {/* Features Section */}
        {!selectedRashi && (
          <div className="mt-16">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold text-main mb-4">
                Why Choose AI Horoscope?
              </h2>
              <p className="text-secondary max-w-2xl mx-auto">
                Advanced AI trained on thousands of Vedic astrology texts
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
              <FeatureCard
                icon="🤖"
                title="AI-Powered"
                description="Advanced AI analyzes Vedic principles in real-time"
              />
              <FeatureCard
                icon="📚"
                title="Authentic Vedic"
                description="Based on traditional Vedic astrology texts"
              />
              <FeatureCard
                icon="🎯"
                title="Highly Detailed"
                description="Specific predictions for each life area"
              />
              <FeatureCard
                icon="🕉️"
                title="Personalized Remedies"
                description="Custom mantras and remedies for your rashi"
              />
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function FeatureCard({ icon, title, description }) {
  return (
    <div className="bg-background rounded-xl shadow-lg p-6 text-center border-2 border-secondary-dark hover:border-primary-main/40 transition-all hover:shadow-xl">
      <div className="text-5xl mb-4">{icon}</div>
      <h3 className="font-bold text-main mb-2">{title}</h3>
      <p className="text-sm text-secondary">{description}</p>
    </div>
  );
}