"use client";

import { useState, useEffect, Suspense } from "react";
import { ArrowLeft, Heart, Share2, Download } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import MatchResult from "@/components/astrology/MatchResult";
import KundaliForm from "@/components/astrology/KundaliForm";

function KundaliMatchingContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [boyData, setBoyData] = useState(null);
  const [girlData, setGirlData] = useState(null);
  const [match, setMatch] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const runMatch = async (boy, girl) => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch("/backend/kundali/match", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          boy: { ...boy, gender: "MALE" }, 
          girl: { ...girl, gender: "FEMALE" } 
        }),
      });

      const data = await response.json();

      if (data.success) {
        setMatch(data.match);
      } else {
        setError(data.error || "Failed to compute match");
      }
    } catch (err) {
      console.error("Matching error:", err);
      setError("Network error. Please check your connection and try again.");
    } finally {
      setLoading(false);
    }
  };

  // Auto-match when coming from home page
  useEffect(() => {
    const autoMatch = searchParams.get('autoMatch');
    
    if (autoMatch === 'true') {
      const boyFormData = {
        name: searchParams.get('boyName'),
        date: searchParams.get('boyDate'),
        time: searchParams.get('boyTime'),
        place: searchParams.get('boyPlace'),
        lat: Number(searchParams.get('boyLat')),
        lng: Number(searchParams.get('boyLng')),
      };

      const girlFormData = {
        name: searchParams.get('girlName'),
        date: searchParams.get('girlDate'),
        time: searchParams.get('girlTime'),
        place: searchParams.get('girlPlace'),
        lat: Number(searchParams.get('girlLat')),
        lng: Number(searchParams.get('girlLng')),
      };

      // Validate that we have all required data
      if (
        boyFormData.name && 
        boyFormData.date && 
        boyFormData.time && 
        boyFormData.place &&
        girlFormData.name && 
        girlFormData.date && 
        girlFormData.time && 
        girlFormData.place
      ) {
        setBoyData(boyFormData);
        setGirlData(girlFormData);
        runMatch(boyFormData, girlFormData);
      } else {
        setError("Incomplete data. Please fill all required fields.");
      }
    }
  }, []);

  const handleBoySubmit = (data) => {
    setBoyData(data);
    if (girlData) {
      runMatch(data, girlData);
    }
  };

  const handleGirlSubmit = (data) => {
    setGirlData(data);
    if (boyData) {
      runMatch(boyData, data);
    }
  };

  const reset = () => {
    setBoyData(null);
    setGirlData(null);
    setMatch(null);
    setError(null);
    // Clear URL params
    router.push('/astrology/kundali-matching');
  };

  const handleDownload = () => {
    if (!match) return;
    
    const content = `
Kundali Matching Report
======================================

Boy's Details:
- Name: ${match.boy.name}
- Rashi: ${match.boy.rashi}
- Nakshatra: ${match.boy.nakshatra}

Girl's Details:
- Name: ${match.girl.name}
- Rashi: ${match.girl.rashi}
- Nakshatra: ${match.girl.nakshatra}

Compatibility Score: ${match.total}/${match.maxTotal} (${Math.round((match.total / match.maxTotal) * 100)}%)

Verdict: ${match.verdict}

Koota Analysis:
${match.kootas.map(k => `- ${k.name}: ${k.score}/${k.max}${k.dosha ? ' (Dosha Present)' : ''}`).join('\n')}

Doshas:
- Nadi Dosha: ${match.doshas.nadi ? 'Yes' : 'No'}
- Bhakoot Dosha: ${match.doshas.bhakoot ? 'Yes' : 'No'}

Generated on: ${new Date().toLocaleDateString()}
Generated by: Free Astrology Services
    `.trim();
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `kundali-matching-${match.boy.name}-${match.girl.name}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (!match) return;
    
    const shareText = `💑 Kundali Matching Result\n\n${match.boy.name} & ${match.girl.name}\n\nCompatibility: ${match.total}/${match.maxTotal} (${Math.round((match.total / match.maxTotal) * 100)}%)\nVerdict: ${match.verdict}\n\nGet your free Kundali matching at: ${window.location.origin}/astrology/kundali-matching`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Kundali Matching Report',
          text: shareText
        });
      } catch (err) {
        console.log('Share cancelled');
      }
    } else {
      navigator.clipboard.writeText(shareText);
      alert('Matching details copied to clipboard!');
    }
  };

  // Get initial data for forms if we're not auto-matching
  const initialBoyData = searchParams.get('autoMatch') !== 'true' ? null : {
    name: searchParams.get('boyName') || '',
    date: searchParams.get('boyDate') || '',
    time: searchParams.get('boyTime') || '',
    place: searchParams.get('boyPlace') || '',
    lat: searchParams.get('boyLat') || '',
    lng: searchParams.get('boyLng') || '',
  };

  const initialGirlData = searchParams.get('autoMatch') !== 'true' ? null : {
    name: searchParams.get('girlName') || '',
    date: searchParams.get('girlDate') || '',
    time: searchParams.get('girlTime') || '',
    place: searchParams.get('girlPlace') || '',
    lat: searchParams.get('girlLat') || '',
    lng: searchParams.get('girlLng') || '',
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-pink-50 via-white to-rose-50">
      {/* Header */}
      <div className="border-b bg-white shadow-sm">
        <div className="mx-auto max-w-7xl px-4 py-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <button
                onClick={() => router.back()}
                className="rounded-lg p-2 transition-colors hover:bg-gray-100"
              >
                <ArrowLeft className="h-5 w-5 text-gray-600" />
              </button>
              <div>
                <h1 className="flex items-center gap-2 text-2xl font-bold text-gray-900 md:text-3xl">
                  <Heart className="h-7 w-7 text-rose-500" />
                  Kundali Matching
                </h1>
                <p className="text-gray-600">
                  Guna Milan compatibility based on birth details of both partners
                </p>
              </div>
            </div>

            {match && (
              <div className="flex items-center space-x-3">
                <button
                  onClick={handleDownload}
                  className="flex items-center space-x-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
                >
                  <Download className="w-4 h-4" />
                  <span className="hidden sm:inline">Download</span>
                </button>
                <button
                  onClick={handleShare}
                  className="flex items-center space-x-2 px-4 py-2 bg-pink-600 text-white rounded-lg hover:bg-pink-700 transition-colors"
                >
                  <Share2 className="w-4 h-4" />
                  <span className="hidden sm:inline">Share</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="mx-auto max-w-7xl px-4 py-8">
        {loading ? (
          <div className="bg-white rounded-xl shadow-lg p-12">
            <div className="text-center">
              <div className="mx-auto mb-4 h-12 w-12 animate-spin rounded-full border-b-2 border-rose-600" />
              <h3 className="text-lg font-medium text-gray-900 mb-2">
                Calculating Compatibility
              </h3>
              <p className="text-gray-600">Analyzing Guna Milan for both partners...</p>
            </div>
          </div>
        ) : error ? (
          <div className="mx-auto max-w-2xl rounded-xl border-2 border-red-200 bg-red-50 p-6">
            <div className="flex items-center space-x-2">
              <span className="text-red-600 text-2xl">⚠️</span>
              <span className="font-semibold text-red-800 text-lg">Error</span>
            </div>
            <p className="mt-2 text-red-700">{error}</p>
            <button
              onClick={reset}
              className="mt-4 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
            >
              Try Again
            </button>
          </div>
        ) : match ? (
          <div className="space-y-6">
            <MatchResult match={match} />
            <div className="text-center">
              <button
                onClick={reset}
                className="inline-block rounded-xl border-2 border-gray-300 bg-white px-8 py-3 font-semibold text-gray-700 transition-all hover:bg-gray-50 hover:shadow-md"
              >
                Check Another Match
              </button>
            </div>
          </div>
        ) : (
          <>
            <div className="bg-pink-50 border border-pink-200 rounded-xl p-6 mb-8">
              <div className="flex items-start space-x-3">
                <Heart className="w-6 h-6 text-pink-600 mt-1 flex-shrink-0" />
                <div>
                  <h3 className="font-semibold text-pink-900 mb-2">How to Check Compatibility</h3>
                  <div className="text-pink-800 space-y-1 text-sm">
                    <p>• Enter birth details for both partners</p>
                    <p>• Include exact birth time and place for accurate results</p>
                    <p>• Get instant Guna Milan compatibility score</p>
                    <p>• View detailed Koota-wise analysis</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="grid gap-8 lg:grid-cols-2">
              <div>
                <h2 className="mb-3 text-center text-lg font-semibold text-gray-800">
                Boy's Birth Details
                </h2>
                <KundaliForm 
                  onSubmit={handleBoySubmit} 
                  loading={loading} 
                  title="Boy's Details"
                  showGender={false}
                  initialData={initialBoyData}
                />
                {boyData && (
                  <p className="mt-2 text-center text-sm text-green-600">
                    ✓ {boyData.name}'s details saved
                  </p>
                )}
              </div>

              <div>
                <h2 className="mb-3 text-center text-lg font-semibold text-gray-800">
                 Girl's Birth Details
                </h2>
                <KundaliForm 
                  onSubmit={handleGirlSubmit} 
                  loading={loading} 
                  title="Girl's Details"
                  showGender={false}
                  initialData={initialGirlData}
                />
                {girlData && (
                  <p className="mt-2 text-center text-sm text-green-600">
                    ✓ {girlData.name}'s details saved
                  </p>
                )}
              </div>
            </div>

            {boyData && girlData && (
              <div className="text-center mt-8">
                <div className="bg-gradient-to-r  from-pink-50 to-rose-50 border-2 border-pink-200 rounded-xl p-6">
                  <p className="text-gray-700 mb-4">
                    Both details are saved! Click below to check compatibility.
                  </p>
                  <button
                    onClick={() => runMatch(boyData, girlData)}
                    disabled={loading}
                    className="bg-gradient-to-r from-pink-600 to-rose-600 text-white px-8 py-3 rounded-xl font-semibold hover:from-pink-700 hover:to-rose-700 transition-all shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {loading ? (
                      <span className="flex items-center justify-center">
                        <span className="mr-2 h-5 w-5 animate-spin rounded-full border-2 border-white border-t-transparent" />
                        Checking Compatibility...
                      </span>
                    ) : (
                      <span className="flex items-center justify-center gap-2">
                        <Heart className="w-5 h-5 fill-white" />
                        Check Compatibility
                      </span>
                    )}
                  </button>
                </div>
              </div>
            )}
          </>
        )}

        {/* Info Section - Only show when no match */}
        {!match && !loading && !error && (
          <div className="mt-16">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold text-gray-900 mb-4">
                What You'll Get
              </h2>
              <p className="text-gray-600 max-w-2xl mx-auto">
                Comprehensive Guna Milan analysis based on Vedic astrology principles
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
              <div className="bg-white rounded-xl shadow-lg p-6 text-center border-2 border-pink-100">
                <div className="w-12 h-12 bg-pink-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-2xl">💯</span>
                </div>
                <h3 className="font-semibold text-gray-900 mb-2">36-Point Analysis</h3>
                <p className="text-sm text-gray-600">Complete Ashtakoot Guna Milan scoring system</p>
              </div>

              <div className="bg-white rounded-xl shadow-lg p-6 text-center border-2 border-pink-100">
                <div className="w-12 h-12 bg-rose-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-2xl">📊</span>
                </div>
                <h3 className="font-semibold text-gray-900 mb-2">8 Kootas</h3>
                <p className="text-sm text-gray-600">Detailed breakdown of all eight compatibility factors</p>
              </div>

              <div className="bg-white rounded-xl shadow-lg p-6 text-center border-2 border-pink-100">
                <div className="w-12 h-12 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-2xl">⚠️</span>
                </div>
                <h3 className="font-semibold text-gray-900 mb-2">Dosha Detection</h3>
                <p className="text-sm text-gray-600">Identifies Nadi and Bhakoot doshas if present</p>
              </div>

              <div className="bg-white rounded-xl shadow-lg p-6 text-center border-2 border-pink-100">
                <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-2xl">💑</span>
                </div>
                <h3 className="font-semibold text-gray-900 mb-2">Compatibility Verdict</h3>
                <p className="text-sm text-gray-600">Clear recommendation based on total score</p>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default function KundaliMatchingPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-pink-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading...</p>
        </div>
      </div>
    }>
      <KundaliMatchingContent />
    </Suspense>
  );
}